### ISSUE TITLE
config out of inventory is not written into rke2_config

### ISSUE THREAD

**Issue by zoop-btc** [rancherfederal/rke2-ansible#123]
I am new to ansible so I might be misunderstanding things. But I had trouble changing the config through the inventory file.

We read into the variable updated_rke_config but disable to signal change.
```
 register: updated_rke2_config
  changed_when: false
```
"Update rke2_config to take value of updated_rke2_config" is thus always skipped and rke2_config is never changed since ` when: updated_rke2_config.changed` is always false.

https://github.com/rancherfederal/rke2-ansible/blob/6d7287311f192039dcd8c2101e724ff1e70ceb6a/roles/rke2_common/tasks/config.yml#L90-L105

After removing the `changed_when:false` it worked as expected.

Is there a reason for this?

**Comment by marcinkubica** [comment]
Looks like this issue https://github.com/rancherfederal/rke2-ansible/issues/138

**Comment by zoop-btc** [comment]
I just removed all  `  changed_when: false ` statements from the file and then it seems to work as it should.

**Comment by marcinkubica** [comment]
@zoop-btc and how your config will look like if you use additional rke_config node-label var like
```
ansible-playbook site.yaml -e '{ "rke2_config" : { "node-label": ["ansibleLabel=true"] }}'
```
I've found it wiping the config

**Comment by zoop-btc** [comment]
You should probably set labels per host in your inventory. Here's an example of mine:
```
all:
  children:
    rke2_agents:
      hosts:
        "node2":
          node_ip: "10.10.10.20"
          ansible_user: root
          node_name: "node2"
          bind_address: "10.10.10.20"
          advertise_adress: "10.10.10.20"
          node_external_ip: "10.10.10.20"
          add_iptables_rules: false
          node_labels:
            - "ingress"
            - "worker"
```
