### ISSUE TITLE
"NetworkManager fix" Ansible task not aligned with Rancher documentation

### ISSUE THREAD

**Issue by aceeric** [rancherfederal/rke2-ansible#137]
Hello - The Rancher documentation [here](https://docs.rke2.io/known_issues#networkmanager) states:

> If you have not yet installed RKE2, a simple systemctl reload NetworkManager will suffice to install the configuration.

However, looking at your _NetworkManager fix_ Ansible task [here](https://github.com/rancherfederal/rke2-ansible/blob/main/roles/rke2_common/tasks/network_manager_fix.yaml), the aforementioned `systemctl` step is missing - and in fact when I run your Ansible installer in RHEL8 with `NetworkManager` running, the `rke2-server` service never starts.

I patched the following as a final task in `network_manager_fix.yaml` at the very end:

```
- name: Reload NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    state: reloaded
  when: (ansible_facts.services["NetworkManager.service"] is defined) and
        (ansible_facts.services["NetworkManager.service"].status == "running")
```

And then the playbook runs to completion on both Centos 7 and RHEL 8 when `NetworkManager` is running and also when it is not running. Please consider adding this additional task to your task file.
