### ISSUE TITLE
CIS Hardening and NFS root squashing

### ISSUE THREAD

**Issue by aceeric** [rancherfederal/rke2-ansible#158]
When `/home` is an NFS volume and root squashing is enabled, and Ansible (as root) tries to `mkdir /home/etcd` it results in an OS error. If the person installer doesn't have the ability to change this then the installation fails. The error occurs here: `roles/rke2_common/tasks/cis-hardening.yml`:
```
    - name: Create etcd user
      user:
        name: etcd
        comment: etcd user
        shell: /bin/nologin
        group: etcd
```
