### ISSUE TITLE
Request for Clarification [setting proxy information]

### ISSUE THREAD

**Issue by ghost** [rancherfederal/rke2-ansible#169]
According to the advanced configuration documentation: https://docs.rke2.io/advanced proxy configurations should be set in `/etc/default/rke2-[server,agent]`.

Is that supported using either settings in `group_vars/...` or `hosts.ini`?

**Comment by jcox10** [comment]
I don't see anything in the roles that sets the the systemd proxy vars. However, you can set containerd to use a mirror to get to docker.io (see [here](https://github.com/rancherfederal/rke2-ansible/blob/main/roles/rke2_common/tasks/add-registry-config.yml)). That file can contain your internal mirror (artifactory, nexus, etc. if you have one).
```yaml
mirrors:
  docker.io:
    endpoint:
      - "https://your-docker-registry.something.com"
```
