### ISSUE TITLE
Parameterize Temporary Directory used during Tarball Install

### ISSUE THREAD

**Issue by robnk23** [rancherfederal/rke2-ansible#172]
During a tarball install the rke2 executable is run from a temporary directory that is created in the system default temp dir, usually `/tmp`. If `/tmp` is mounted with the `noexec` option the tarball install will fail.

The task that creates the temporary directory is here:
```
roles/rke2_common/tasks/tarball_install.yml
---
- name: TARBALL | Make temp dir
  ansible.builtin.tempfile:
    state: directory
    suffix: rke2-install.XXXXXXXXXX
  register: temp_dir
```
