### ISSUE TITLE
Clarification request regarding hosts.yml

### ISSUE THREAD

**Issue by GoldennDragonn** [rancherfederal/rke2-ansible#232]
Good morning, if using the new hosts.yml - does the rke2-server and rke2-agent.yml needed? And if there is a mismatch in configuration between hosts.yml and the files above - does host.yml is the one that will be used?

**Comment by Eric-Domeier** [comment]
You can use a mixture of both, or put them all in hosts.yml you are looking for ansible variable precedence

https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

The rke2-server and rke-agent files are inventory group vars (Precedence of 6) 
and the hosts.yml file are inventory host_vars (Precedence 9)

Therefore if there are conflicting variables, the vars in hosts.yml will win

Ansible suggests that all vars should be defined in one place per that page though it's up to you.

**Comment by Eric-Domeier** [comment]
> Thank you for clarification. The question raised after running the latest playbook and the config.yaml was empty, even though it was defined in host.yml. So my initial thought was that rke2-servers and rke2-agent override hosts,yml. Will do some more tests.

If you can provide a copy of your server, agent and hosts yaml's I can see if I spot anything off

**Comment by GoldennDragonn** [comment]
Sure. 
---
all:
  vars:
    install_rke2_version: v1.27.13+rke2r1
    # # In air-gapped envs, it might be convenient to download the tar files from custom URLs
    # rke2_tarball_url: https://github.com/rancher/rke2/releases/download/v1.26.15%2Brke2r1/rke2.linux-amd64.tar.gz
    # rke2_image_tar_urls:
    # - https://github.com/rancher/rke2/releases/download/v1.26.15%2Brke2r1/rke2-images-canal.linux-amd64.tar.zst
    # - https://github.com/rancher/rke2/releases/download/v1.26.15%2Brke2r1/rke2-images-core.linux-amd64.tar.zst

rke2_cluster:
  children:
    rke2_servers:
      vars:
        # # Set generic rke2_config at the group level.
        # # Every host in this group will inherit these rke2 configurations
        # # See https://docs.rke2.io/reference/server_config for more options
        # # These options can also be set in the group_vars folder
        rke2_config:
          # node-label:
          #   - serverGroupLabel=true
          profile: cis
          cni: calico
          disable: 
            - rke2-canal
            - rke2-ingress-nginx
          # kube-controller-manager-arg:
          # - "tls-min-version=VersionTLS12"
          # - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
          # kube-scheduler-arg:
          # - "tls-min-version=VersionTLS12"
          # - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
          # kube-apiserver-arg:
          # - "tls-min-version=VersionTLS12"
          # - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
          # - "enable-admission-plugins=ValidatingAdmissionWebhook,NodeRestriction,PodSecurityPolicy"
          # - "request-timeout=300s"
          # # Enable only when auditing is enabled, blocks API when audit fails
          # #- "audit-log-mode=blocking-strict"
          #
          # kubelet-arg:
          # - "feature-gates=DynamicKubeletConfig=false"
          # - "protect-kernel-defaults=true"
          # - "streaming-connection-idle-timeout=5m"
          #
          # etcd-extra-env:
          # - "ETCD_AUTO_TLS=false"
          # - "ETCD_PEER_AUTO_TLS=false"
          #
          admission-control-config-file: "/etc/rancher/rke2/pod-security-admission-config.yaml"

          write-kubeconfig-mode: "0640"
          # # See https://kubernetes.io/docs/tasks/debug-application-cluster/audit/
          # # Add a policy configuration file by specifying the file path on the control host
          audit_policy_config_file_path: "{{ playbook_dir }}/extraconfigs/audit-policy.yaml"
          # # See https://docs.rke2.io/install/containerd_registry_configuration/
          # # Add a registry configuration file by specifying the file path on the control host
          registry_config_file_path: "{{ playbook_dir }}/extraconfigs/registries.yaml"
          # # See https://docs.rke2.io/helm/#automatically-deploying-manifests-and-helm-charts
          # # Add manifest files by specifying the directory path on the control host
          manifest_config_file_path: "{{ playbook_dir }}/extraconfigs/manifest/"
          # See https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/psa-config-templates#exempting-required-rancher-namespaces
          # Available in RKE2 1.25+
          # Add a pod security admission config file by specifying the file path on the control host
          # Requires config.yaml to include `- admission-control-config-file=/etc/rancher/rke2/pod-security-admission-config.yaml` in order for this to be honored
          pod_security_admission_config_file_path: "{{ playbook_dir }}/extraconfigs/pod-security-admission-config.yaml"
      hosts:
        # # Optional hostvars that can be pased in to individual nodes include
        # # node_ip, node_name, bind_address, advertise_address, node_taints=[],
        # # node_labels=[], and node_external_ip
        192.168.56.101:
          # node_labels:
          #   - server0Label=true
          node_ip: "192.168.56.101"
          # node_name: "server0.example.com"
          # bind_address: "10.10.10.10"
          # advertise_address: "10.10.10.10"
          # node_external_ip: "52.52.52.52"
          # node_taints:
          # - CriticalAddonsOnly=true:NoSchedule
          # cloud_provider_name: "aws"
        192.168.56.102:
          # node_labels:
          #   - server0Label=true
          node_ip: "192.168.56.102"
        192.168.56.103:
          # node_labels:
          #   - server0Label=true
          node_ip: "192.168.56.103"
    rke2_agents:
      vars:
        rke2_config:
          # node-label:
          #   - agentGroupLabel=true
          
      # hosts:
      #   agent0.example.com:
      #     # node_labels:
      #     #   - agent0Label=true
      #     # node_ip: "10.10.10.10"
      #   agent1.example.com:
      #     # node_labels:
      #     #   - agent1Label=true
      #     # node_ip: "10.10.10.10"
rke2-agents and rke2-servers are default (didn't touch them) and my config.yaml in each server is empty. 

node-ip: 192.168.56.101
node-label: []
node-taint: []

**Comment by GoldennDragonn** [comment]
As far as I see, the var in hosts.yml like cni, cis profile are totally ignored...

**Comment by GoldennDragonn** [comment]
Update: I've commented rke_config: {} in rke2_servers and rke2_agents - and the var from hosts.yml were respected. However the indetnation of the : 
audit_policy_config_file_path: "{{ playbook_dir }}/extraconfigs/audit-policy.yaml"
          # # See https://docs.rke2.io/install/containerd_registry_configuration/
          # # Add a registry configuration file by specifying the file path on the control host
          registry_config_file_path: "{{ playbook_dir }}/extraconfigs/registries.yaml"
          # # See https://docs.rke2.io/helm/#automatically-deploying-manifests-and-helm-charts
          # # Add manifest files by specifying the directory path on the control host
          manifest_config_file_path: "{{ playbook_dir }}/extraconfigs/manifest/"
is not correct... it is pasted as is to config,yaml. I believe it should be aligned the same way as it is in rke2_servers.yml.

**Comment by GoldennDragonn** [comment]
Update: Attaching the configuration that successfully worked. 
```
---
all:
  vars:
    install_rke2_version: v1.27.13+rke2r1
    # # In air-gapped envs, it might be convenient to download the tar files from custom URLs
    # rke2_tarball_url: https://github.com/rancher/rke2/releases/download/v1.26.15%2Brke2r1/rke2.linux-amd64.tar.gz
    # rke2_image_tar_urls:
    # - https://github.com/rancher/rke2/releases/download/v1.26.15%2Brke2r1/rke2-images-canal.linux-amd64.tar.zst
    # - https://github.com/rancher/rke2/releases/download/v1.26.15%2Brke2r1/rke2-images-core.linux-amd64.tar.zst

rke2_cluster:
  children:
    rke2_servers:
      vars:
        # # Set generic rke2_config at the group level.
        # # Every host in this group will inherit these rke2 configurations
        # # See https://docs.rke2.io/reference/server_config for more options
        # # These options can also be set in the group_vars folder
        rke2_config:
          node-label:
            - masters=true
          profile: cis-1.23
          cni: 
            - calico
          disable: 
            - rke2-canal
            - rke2-ingress-nginx
          # kube-controller-manager-arg:
          # - "tls-min-version=VersionTLS12"
          # - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
          # kube-scheduler-arg:
          # - "tls-min-version=VersionTLS12"
          # - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
          # kube-apiserver-arg:
          # - "tls-min-version=VersionTLS12"
          # - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
          # - "enable-admission-plugins=ValidatingAdmissionWebhook,NodeRestriction,PodSecurityPolicy"
          # - "request-timeout=300s"
          # # Enable only when auditing is enabled, blocks API when audit fails
          # #- "audit-log-mode=blocking-strict"
          #
          # kubelet-arg:
          # - "feature-gates=DynamicKubeletConfig=false"
          # - "protect-kernel-defaults=true"
          # - "streaming-connection-idle-timeout=5m"
          #
          # etcd-extra-env:
          # - "ETCD_AUTO_TLS=false"
          # - "ETCD_PEER_AUTO_TLS=false"
          #
          admission-control-config-file: "/etc/rancher/rke2/pod-security-admission-config.yaml"

          write-kubeconfig-mode: "0644"
        # # See https://kubernetes.io/docs/tasks/debug-application-cluster/audit/
        # # Add a policy configuration file by specifying the file path on the control host
        audit_policy_config_file_path: "{{ playbook_dir }}/extraconfigs/audit-policy.yaml"
        # # See https://docs.rke2.io/install/containerd_registry_configuration/
        # # Add a registry configuration file by specifying the file path on the control host
        registry_config_file_path: "{{ playbook_dir }}/extraconfigs/registries.yaml"
        # # See https://docs.rke2.io/helm/#automatically-deploying-manifests-and-helm-charts
        # # Add manifest files by specifying the directory path on the control host
        manifest_config_file_path: "{{ playbook_dir }}/extraconfigs/manifest/"
        # See https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/psa-config-templates#exempting-required-rancher-namespaces
        # Available in RKE2 1.25+
        # Add a pod security admission config file by specifying the file path on the control host
        # Requires config.yaml to include `- admission-control-config-file=/etc/rancher/rke2/pod-security-admission-config.yaml` in order for this to be honored
        pod_security_admission_config_file_path: "{{ playbook_dir }}/extraconfigs/pod-security-admission-config.yaml"
      hosts:
        # # Optional hostvars that can be pased in to individual nodes include
        # # node_ip, node_name, bind_address, advertise_address, node_taints=[],
        # # node_labels=[], and node_external_ip
        192.168.56.101:
          # node_labels:
          #   - server0Label=true
          node_ip: "192.168.56.101"
          # node_name: "server0.example.com"
          # bind_address: "10.10.10.10"
          # advertise_address: "10.10.10.10"
          # node_external_ip: "52.52.52.52"
          # node_taints:
          # - CriticalAddonsOnly=true:NoSchedule
          # cloud_provider_name: "aws"
        192.168.56.102:
          # node_labels:
          #   - server0Label=true
          node_ip: "192.168.56.102"
        192.168.56.103:
          # node_labels:
          #   - server0Label=true
          node_ip: "192.168.56.103"
    rke2_agents:
      vars:
        rke2_config:
          # node-label:
          #   - agentGroupLabel=true
          
      # hosts:
      #   agent0.example.com:
      #     # node_labels:
      #     #   - agent0Label=true
      #     # node_ip: "10.10.10.10"
      #   agent1.example.com:
      #     # node_labels:
      #     #   - agent1Label=true
      #     # node_ip: "10.10.10.10"

```
