### ISSUE TITLE
Agent Nodes not showing up or usable despite the service running on the machine

### ISSUE THREAD

**Issue by R4tchi** [rancherfederal/rke2-ansible#245]
Hi!

Im trying to deploy the RKE2 Cluster via your Ansible Repository. Everything seems to work and i get no error message. After the script is done, i can see, that the RKE2 cluster is running and that i have master node within it. But the agent nodes are not inside the cluster. 

I checked the machines and the rke2-agent.service seems to be running. Despite that, i cant deploy pods on the nodes, because they are not inside the cluster. When i use "kubectl get nodes --all-namespaces", only the master node shows up.

The 3 machines that i am running are on the cloud plattform IONOS.

I was guessing that maybe my host file is wrongly configured, but the Master Nodes seems to be working. I tried out different variations and configurations. This configuration is closest to the sample of the inventory in the repository. Only the host file was configured and the rest is untouched. If there is anything i left out in this issue, please let me know. 

I appreciate your help and wish you a nice day!

This is my host file:

```
rke2_cluster:
  children:
    rke2_servers:
      hosts:
        <external IP of the machine>:
          ansible_user: <user>
          ansible_ssh_private_key_file: /path/to/private-key
    rke2_agents:
      vars:
        rke2_config:
          node-label:
           - agentGroupLabel=true
      hosts:
        <external IP of the machine>:
          ansible_user: <user>
          ansible_ssh_private_key_file: /path/to/private-key
          rke2_config:
            node_label:
              - agent0Label=true
        <external IP of the machine>:
          ansible_user: <user>
          ansible_ssh_private_key_file: /path/to/private-key
          rke2_config:
            node_label:
              - agent1Label=true
all:
  vars:
    install_rke2_version: v1.27.10+rke2r1
```

**Comment by R4tchi** [comment]
After checking the service:

```
Jun 13 11:27:34 ubuntu rke2[42013]: time="2024-06-13T11:27:34Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: Node password rejected, duplicate hostname or contents of '/etc/rancher/node/password' may not match server node-passwd entry, try enabling a unique node name with the --with-node-id flag"
```

**Comment by aleiner** [comment]
@R4tchi - are you specifying the join token as a variable or setting the `token` line as a variable for the config.yaml file?

**Comment by R4tchi** [comment]
If i understand it correctly, than the latter. This is my config.yml file:

```
---
- name: Create the /etc/rancher/rke2 config dir
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    mode: "0750"

- name: Does the /etc/rancher/rke2/config.yaml file exist?
  ansible.builtin.stat:
    path: /etc/rancher/rke2/config.yaml
  register: previous_rke2_config

- name: Read previous_rke2_config
  ansible.builtin.slurp:
    src: /etc/rancher/rke2/config.yaml
  register: full_orig_rke2_config
  when: previous_rke2_config.stat.exists

- name: Decode contents of slurp
  ansible.builtin.set_fact:
    orig_rke2_config: "{{ full_orig_rke2_config['content'] | b64decode }}"
  when: previous_rke2_config.stat.exists

- name: Create the /etc/rancher/rke2/config.yaml file
  ansible.builtin.file:
    path: /etc/rancher/rke2/config.yaml
    state: touch
    mode: "0640"
    owner: root
    group: root
  when: not previous_rke2_config.stat.exists

# https://github.com/ansible-collections/ansible.utils/issues/135
- name: Ensure Ansible renders any templated variables in rke2_config
  ansible.builtin.set_fact:
    rke2_config: "{{ rke2_config | default({}) }}"

# --node-label value                     (agent/node) Registering and starting kubelet with set of labels
- name: Get rke2_config node-labels
  ansible.builtin.set_fact:
    rke2_config_node_labels: "{{ rke2_config['node-label'] | default([]) }}"

- name: Get host var node-labels
  ansible.builtin.set_fact:
    host_var_node_labels: "{{ node_labels | default([]) }}"

- name: Combine rke2_config node labels and hostvar node labels
  ansible.builtin.set_fact:
    all_node_labels: "{{ rke2_config_node_labels + host_var_node_labels }}"
  changed_when: false

- name: Add node labels to rke2_config
  ansible.utils.update_fact:
    updates:
      - path: rke2_config["node-label"]
        value: "{{ all_node_labels }}"
  register: updated_rke2_config
  changed_when: false

- name: Update rke2_config to take value of updated_rke2_config
  ansible.builtin.set_fact:
    rke2_config: "{{ updated_rke2_config.rke2_config }}"
  changed_when: false

# --node-taint value                     (agent/node) Registering kubelet with set of taints
- name: Get rke2_config node-taints
  ansible.builtin.set_fact:
    rke2_config_node_taints: "{{ rke2_config['node-taint'] | default([]) }}"

- name: Get host var node-taints
  ansible.builtin.set_fact:
    host_var_node_taints: "{{ node_taints | default([]) }}"

- name: Combine rke2_config node taints and hostvar node taints
  ansible.builtin.set_fact:
    all_node_taints: "{{ rke2_config_node_taints + host_var_node_taints }}"
  changed_when: false

- name: Add node labels to rke2_config
  ansible.utils.update_fact:
    updates:
      - path: rke2_config["node-taint"]
        value: "{{ all_node_taints }}"
  register: updated_rke2_config
  changed_when: false

- name: Update rke2_config to take value of updated_rke2_config
  ansible.builtin.set_fact:
    rke2_config: "{{ updated_rke2_config.rke2_config }}"
  changed_when: false

# --node-ip value, -i value (agent/networking) IPv4/IPv6 addresses to advertise for node
- name: Add node-ip to rke2_config
  ansible.utils.update_fact:
    updates:
      - path: rke2_config["node-ip"]
        value: "{{ node_ip }}"
  when: (node_ip is defined) and (node_ip|length > 0)
  register: updated_rke2_config
  changed_when: false

- name: Update rke2_config to take value of updated_rke2_config  # noqa no-handler
  ansible.builtin.set_fact:
    rke2_config: "{{ updated_rke2_config.rke2_config }}"
  when: (node_ip is defined) and (node_ip|length > 0)
  changed_when: false

# --node-name value (agent/node) Node name [$RKE2_NODE_NAME]
- name: Add node-name to rke2_config
  ansible.utils.update_fact:
    updates:
      - path: rke2_config["node-name"]
        value: "{{ node_name }}"
  when: (node_name is defined) and (node_name|length > 0)
  register: updated_rke2_config
  changed_when: false

- name: Update rke2_config to take value of updated_rke2_config  # noqa no-handler
  ansible.builtin.set_fact:
    rke2_config: "{{ updated_rke2_config.rke2_config }}"
  when: (node_name is defined) and (node_name|length > 0)
  changed_when: false

# --bind-address value (listener) rke2 bind address (default: 0.0.0.0)
- name: Add bind-address to rke2_config
  ansible.utils.update_fact:
    updates:
      - path: rke2_config["bind-address"]
        value: "{{ bind_address }}"
  when: (bind_address is defined) and (bind_address|length > 0)
  register: updated_rke2_config
  changed_when: false

- name: Update rke2_config to take value of updated_rke2_config  # noqa no-handler
  ansible.builtin.set_fact:
    rke2_config: "{{ updated_rke2_config.rke2_config }}"
  when: (bind_address is defined) and (bind_address|length > 0)
  changed_when: false

# --advertise-address value (listener) IPv4 address that apiserver uses
# to advertise to members of the cluster (default: node-external-ip/node-ip)
- name: Add advertise-address to rke2_config
  ansible.utils.update_fact:
    updates:
      - path: rke2_config["advertise-address"]
        value: "{{ advertise_address }}"
  when: (advertise_address is defined) and (advertise_address|length > 0)
  register: updated_rke2_config
  changed_when: false

- name: Update rke2_config to take value of updated_rke2_config  # noqa no-handler
  ansible.builtin.set_fact:
    rke2_config: "{{ updated_rke2_config.rke2_config }}"
  when: (advertise_address is defined) and (advertise_address|length > 0)
  changed_when: false

# --node-external-ip value (agent/networking) IPv4/IPv6 external IP addresses to advertise for node
- name: Add node-external-ip to rke2_config
  ansible.utils.update_fact:
    updates:
      - path: rke2_config["node-external-ip"]
        value: "{{ node_external_ip }}"
  when: (node_external_ip is defined) and (node_external_ip|length > 0)
  register: updated_rke2_config
  changed_when: false

- name: Update rke2_config to take value of updated_rke2_config  # noqa no-handler
  ansible.builtin.set_fact:
    rke2_config: "{{ updated_rke2_config.rke2_config }}"
  when: (node_external_ip is defined) and (node_external_ip|length > 0)
  changed_when: false

# --cloud-provider-name value (agent/node) Cloud provider name
- name: Add cloud-provider-name to rke2_config
  ansible.utils.update_fact:
    updates:
      - path: rke2_config["cloud-provider-name"]
        value: "{{ cloud_provider_name }}"
  when: (cloud_provider_name is defined) and (cloud_provider_name|length > 0)
  register: updated_rke2_config

- name: Update rke2_config to take value of updated_rke2_config  # noqa no-handler
  ansible.builtin.set_fact:
    rke2_config: "{{ updated_rke2_config.rke2_config }}"
  when: (cloud_provider_name is defined) and (cloud_provider_name|length > 0)

- name: Remove tmp config file
  ansible.builtin.file:
    path: /tmp/ansible-config.txt
    state: absent
  changed_when: false

- name: Create tmp config.yaml
  ansible.builtin.copy:
    content: "{{ rke2_config | to_nice_yaml(indent=0) }}"
    dest: /tmp/ansible-config.txt
    mode: "0600"
    owner: root
    group: root
  changed_when: false

- name: Get original token
  ansible.builtin.set_fact:
    original_token: "{{ orig_rke2_config | regex_search('token: (.+)') }}"
  when: previous_rke2_config.stat.exists
  changed_when: false

- name: Add token to config.yaml
  ansible.builtin.lineinfile:
    dest: /tmp/ansible-config.txt
    line: "{{ original_token }}"
    state: present
    insertbefore: BOF
  when: previous_rke2_config.stat.exists and original_token | length > 0
  changed_when: false

- name: Get original server
  ansible.builtin.set_fact:
    original_server: "{{ orig_rke2_config | regex_search('server: https://(.*):9345') }}"
  when: previous_rke2_config.stat.exists
  changed_when: false

- name: Add server url to config file
  ansible.builtin.lineinfile:
    dest: /tmp/ansible-config.txt
    line: "{{ original_server }}"
    state: present
    insertbefore: BOF
  when: previous_rke2_config.stat.exists and original_server | length > 0
  changed_when: false

- name: Stat tmp config
  ansible.builtin.stat:
    path: /tmp/ansible-config.txt
  register: tmp_config
  changed_when: false

- name: Get cksum of tmp config
  ansible.builtin.set_fact:
    tmp_sha1: "{{ tmp_config.stat.checksum }}"
  changed_when: false

- name: Drop in final /etc/rancher/rke2/config.yaml
  ansible.builtin.copy:
    src: /tmp/ansible-config.txt
    remote_src: yes
    dest: /etc/rancher/rke2/config.yaml
    mode: "0640"
    owner: root
    group: root
    backup: yes
  when: not previous_rke2_config.stat.exists or (tmp_sha1 != previous_rke2_config.stat.checksum)

- name: Remove tmp config file
  ansible.builtin.file:
    path: /tmp/ansible-config.txt
    state: absent
  changed_when: false

- name: Restart rke2-server if package installed and config changed or RKE2 version changed
  ansible.builtin.service:
    state: restarted
    name: rke2-server
  when:
    - ansible_facts.services["rke2-server.service"] is defined
    - "ansible_facts.services['rke2-server.service'].state == 'running'"
    - (tmp_sha1 != previous_rke2_config.stat.checksum or (rke2_version_changed | default(false)))

- name: Restart rke2-agent if package installed and config changed or RKE2 version changed
  ansible.builtin.service:
    state: restarted
    name: rke2-agent
  when:
    - ansible_facts.services["rke2-agent.service"] is defined
    - "ansible_facts.services['rke2-agent.service'].state == 'running'"
    - (tmp_sha1 != previous_rke2_config.stat.checksum or (rke2_version_changed | default(false)))
```

While the Ansible Playbook was running, it got always stuck at the "Add server url to config file".
