### ISSUE TITLE
Stagger start RKE2 server nodes

### ISSUE THREAD

**Issue by mddamato** [rancherfederal/rke2-ansible#33]
To avoid any race conditions and a lot of error logs of servers that can't start until the first server is healthy and learner promotions are completed we should block starting/restarting servers until they are showing Ready state.

A possible solution is polling something like this on the host in question until `True` is observed.
 
```
/var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml \
--server https://127.0.0.1:6443 get no {{ inventory_hostname }} \
-o jsonpath='{.status.conditions[?(@.type=="Ready")].status}'
```

**Comment by AYDEV-FR** [comment]
Hi,
I think there is another possible solution. An another point of view.
If I understand correctly, the idea is wait until the kubeapi is up and running ?

There is a more "ansible" approach I think with the module: [ansible.builtin.wait_for](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/wait_for_module.html)
You can add :
```
- name: Wait for k8s apiserver
  wait_for:
    host: "{{ kubernetes_api_server_host }}"
    port: "6443"
    state: present
    timeout: 300
```

This is what kubespray seems to do that here:
https://github.com/kubernetes-sigs/kubespray/blob/33a60fe919b50a149ef6402f56e342989f6eea23/roles/kubernetes/client/tasks/main.yml#L44
