### ISSUE TITLE
Ironbank configuration

### ISSUE THREAD

**Issue by mddamato** [rancherfederal/rke2-ansible#53]
Add ability to switch on or add configuration required to use ironbank versions of RKE2 images

**Comment by Yantrio** [comment]
I hit this recently, and I achieved it by editing the rke2_config var section to include the following:

```yaml
   rke2_config:
      disable: rke2-ingress-nginx
      selinux: true
      protect-kernel-defaults: true
      profile: cis-1.5
      write-kubeconfig-mode: "0640"
      kube-apiserver-image: "registry1.dso.mil/ironbank/rancher-federal/rke2/hardened-kubernetes:v1.20.6-rke2r1"
      kube-controller-manager-image: "registry1.dso.mil/ironbank/rancher-federal/rke2/hardened-kubernetes:v1.20.6-rke2r1"
      kube-scheduler-image: "registry1.dso.mil/ironbank/rancher-federal/rke2/hardened-kubernetes:v1.20.6-rke2r1"
      pause-image: "registry1.dso.mil/ironbank/rancher-federal/rke2/pause:3.2"
      runtime-image: "registry1.dso.mil/ironbank/rancher-federal/rke2/rke2-runtime:v1.20.6-rke2r1"
      etcd-image: "registry1.dso.mil/ironbank/opensource/etcd/etcd:v3.4.15"
      audit-policy-file: /var/lib/rancher/rke2/auditpolicy.yaml
```
